#!/bin/bash
# ─────────────────────────────────────────────────────────
# NorrisPalace → Claude.ai Bridge
# Exports Palace data to a Google Doc for Claude.ai context.
#
# Uses gog CLI to create/update Google Docs.
#
# Usage:
#   bash palace-to-claude.sh            # Silent run (no Telegram)
#   bash palace-to-claude.sh --notify   # With Telegram notification
# ─────────────────────────────────────────────────────────

set -euo pipefail

AGENT_DIR="$HOME/norris-agent"
SCRIPTS_DIR="$AGENT_DIR/scripts"
PYTHON="$AGENT_DIR/.venv/bin/python3"
NP="$SCRIPTS_DIR/norris-palace.py"
GOG="/opt/homebrew/bin/gog"
GOG_ACCOUNT="acnorris@norrisutilities.com"
LOG_FILE="$AGENT_DIR/logs/palace-bridge.log"
URL_FILE="$AGENT_DIR/palace-claude-bridge-url.txt"
DOC_ID_FILE="$AGENT_DIR/palace-claude-doc-id.txt"
DOC_TITLE="NorrisPalace — Daily Context Export for Claude.ai"
TMP_DIR="$AGENT_DIR/tmp"
NOTIFY=false

# Parse args
for arg in "$@"; do
    if [ "$arg" = "--notify" ]; then
        NOTIFY=true
    fi
done

# Ensure dirs
mkdir -p "$AGENT_DIR/logs" "$TMP_DIR"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
TODAY=$(date '+%B %-d, %Y')
EXPORT_FILE="$TMP_DIR/palace_bridge_export.txt"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"; }

log "Bridge run starting (notify=$NOTIFY)..."

# ── Thing 1: Run NorrisPalace full export ───────────────
FULL_EXPORT=$($PYTHON "$NP" export --wing all 2>&1) || true

# ── Thing 2: Run context brief ──────────────────────────
CONTEXT_BRIEF=$($PYTHON "$NP" context-brief 2>&1) || true

# ── Count records ───────────────────────────────────────
RECORD_COUNT=$(echo "$FULL_EXPORT" | grep -c "^### " || echo "0")

# ── Extract sections from full export ───────────────────
# Urgent items: tagged urgent or follow-up
URGENT_ITEMS=$($PYTHON "$NP" query "urgent" --top 10 2>&1) || true
FOLLOWUP_ITEMS=$($PYTHON "$NP" query "follow-up" --top 10 2>&1) || true

# Active deals (wing: deals)
ACTIVE_DEALS=$(echo "$FULL_EXPORT" | sed -n '/^## DEALS/,/^## [A-Z]/p' | sed '$d') || true

# Rules tagged always-check
ALWAYS_CHECK=$($PYTHON "$NP" query "always-check" --top 30 2>&1) || true

# Full customer wing
FULL_CUSTOMERS=$(echo "$FULL_EXPORT" | sed -n '/^## CUSTOMERS/,/^## [A-Z]/p' | sed '$d') || true

# Full rules wing
FULL_RULES=$(echo "$FULL_EXPORT" | sed -n '/^## RULES/,/^## [A-Z]/p' | sed '$d') || true

# ── Thing 3: Combine into one clean document ────────────
cat > "$EXPORT_FILE" << DOCEOF
NorrisPalace Daily Export — $TODAY
Generated: $TIMESTAMP
Total Records: $RECORD_COUNT
═══════════════════════════════════════════════════════

SECTION 1: CONTEXT BRIEF
─────────────────────────────────────────────────────
$CONTEXT_BRIEF

SECTION 2: URGENT ITEMS
─────────────────────────────────────────────────────
--- Tagged "urgent" ---
$URGENT_ITEMS

--- Tagged "follow-up" ---
$FOLLOWUP_ITEMS

SECTION 3: ACTIVE DEALS
─────────────────────────────────────────────────────
$ACTIVE_DEALS

SECTION 4: RULES TO ALWAYS CHECK
─────────────────────────────────────────────────────
$ALWAYS_CHECK

SECTION 5: FULL CUSTOMER WING
─────────────────────────────────────────────────────
$FULL_CUSTOMERS

SECTION 6: FULL RULES WING
─────────────────────────────────────────────────────
$FULL_RULES

═══════════════════════════════════════════════════════
End of NorrisPalace export — $RECORD_COUNT records
Generated by palace-to-claude.sh on $(hostname) at $TIMESTAMP
DOCEOF

# ── Thing 4: Save to Google Drive as a Google Doc ───────

# Check if we already have a doc ID saved
DOC_ID=""
if [ -f "$DOC_ID_FILE" ]; then
    DOC_ID=$(cat "$DOC_ID_FILE" | tr -d '[:space:]')
fi

# If no saved ID, search for existing doc
if [ -z "$DOC_ID" ]; then
    SEARCH_RESULT=$($GOG drive search "NorrisPalace Daily Context Export" \
        --account "$GOG_ACCOUNT" --json --results-only 2>/dev/null) || true
    DOC_ID=$(echo "$SEARCH_RESULT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    files = data if isinstance(data, list) else data.get('files', [])
    for f in files:
        if 'NorrisPalace' in f.get('name','') and f.get('mimeType','') == 'application/vnd.google-apps.document':
            print(f['id']); break
except: pass
" 2>/dev/null) || true
fi

# If still no doc, create one
if [ -z "$DOC_ID" ]; then
    log "Creating new Google Doc: $DOC_TITLE"
    CREATE_OUT=$($GOG docs create "$DOC_TITLE" \
        --account "$GOG_ACCOUNT" --json --results-only 2>&1) || true
    DOC_ID=$(echo "$CREATE_OUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('documentId', data.get('id', '')))
except: pass
" 2>/dev/null) || true
    if [ -z "$DOC_ID" ]; then
        log "ERROR: Failed to create Google Doc — $CREATE_OUT"
        echo "ERROR: Failed to create Google Doc"
        exit 1
    fi
    echo "$DOC_ID" > "$DOC_ID_FILE"
    log "Created doc: $DOC_ID"
fi

# Write content to the doc (replaces body)
WRITE_OUT=$($GOG docs write "$DOC_ID" --file "$EXPORT_FILE" \
    --account "$GOG_ACCOUNT" --force 2>&1) || {
    log "ERROR: gog docs write failed — $WRITE_OUT"
    # Fall back to Python updater if gog fails
    if [ -f "$SCRIPTS_DIR/gdoc_updater.py" ]; then
        log "Falling back to Python gdoc_updater..."
        $PYTHON "$SCRIPTS_DIR/gdoc_updater.py" "$EXPORT_FILE" 2>&1 || true
    fi
}

# Save doc ID and URL
echo "$DOC_ID" > "$DOC_ID_FILE"
DOC_URL="https://docs.google.com/document/d/${DOC_ID}/edit"
echo "$DOC_URL" > "$URL_FILE"

# ── Log the run ────────────────────────────────────────
log "Export complete — $RECORD_COUNT records — $DOC_URL"

# ── Telegram notification (only with --notify) ─────────
if [ "$NOTIFY" = true ]; then
    # Load env
    if [ -f "$AGENT_DIR/.env" ]; then
        export $(grep -v '^#' "$AGENT_DIR/.env" | xargs)
    fi
    if [ -f "$HOME/.openclaw/.env" ]; then
        export $(grep -v '^#' "$HOME/.openclaw/.env" | xargs)
    fi

    BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
    CHAT_ID="${TELEGRAM_CHAT_ID:-8758078447}"
    RUN_TIME=$(date '+%-I:%M %p')

    if [ -n "$BOT_TOKEN" ]; then
        MSG="📚 NorrisPalace synced to Claude.ai — $RECORD_COUNT records exported $RUN_TIME"
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="$MSG" > /dev/null 2>&1 || true
    fi
fi

log "Bridge complete. URL: $DOC_URL"
echo "Bridge complete — $RECORD_COUNT records"
echo "Google Doc URL: $DOC_URL"
